[package]
name = "asset-hub-kusama-emulated-chain"
authors.workspace = true
edition.workspace = true
version.workspace = true
license = "Apache-2.0"
description = "Asset Hub Kusama emulated chain used for integration tests"
publish = false

[dependencies]

# Substrate
sp-core = { workspace = true, default-features = true }
sp-keyring = { workspace = true }
frame-support = { workspace = true, default-features = true }

# Cumulus
parachains-common = { workspace = true, default-features = true }
cumulus-primitives-core = { workspace = true, default-features = true }
emulated-integration-tests-common = { workspace = true }
xcm = { workspace = true, default-features = true }
xcm-builder = { workspace = true, default-features = true }
polkadot-parachain-primitives = { workspace = true }

# Runtimes
asset-hub-kusama-runtime = { workspace = true }
kusama-emulated-chain = { workspace = true }
penpal-emulated-chain = { workspace = true }


# Emulated tests
integration-tests-helpers = { workspace = true }

[features]
runtime-benchmarks = [
	"asset-hub-kusama-runtime/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"integration-tests-helpers/runtime-benchmarks",
	"kusama-emulated-chain/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",

	"polkadot-parachain-primitives/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm/runtime-benchmarks",
]
