rules:
  - name: CI Files
    condition:
      include:
        - ^\.github/.*
    type: basic
    minFellowsRank: 6
    min_approvals: 2
  - name: Relay and system files
    condition:
      include:
        - ^relay\/kusama\/.*
        - ^relay\/polkadot\/.*
        - ^system-parachains\/.*
      exclude: 
        - ^relay\/.+\.adoc$
    type: basic
    minFellowsRank: 3
    min_approvals: 4
  - name: General Files
    condition:
      include:
        - '.*'
      exclude: 
        - ^relay\/kusama\/.*
        - ^relay\/polkadot\/.*
        - ^\.github/.*
        - ^system-parachains\/.*
        - ^target\/.*
    type: basic
    minFellowsRank: 2
