[package]
name = "pallet-ah-migrator"
description = "Operational pallet managing and processing migration from Relay Chain to Asset Hub on Asset Hub"
license = "Apache-2.0"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
codec = { workspace = true, features = ["max-encoded-len"] }
cumulus-primitives-core = { workspace = true }
chrono = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
log = { workspace = true }
assets-common = { workspace = true }
parachains-common = { workspace = true }
impl-trait-for-tuples = { workspace = true }
pallet-asset-rate = { workspace = true }
pallet-balances = { workspace = true }
pallet-bags-list = { workspace = true }
pallet-bounties = { workspace = true }
pallet-conviction-voting = { workspace = true }
pallet-fast-unstake = { workspace = true }
pallet-multisig = { workspace = true }
pallet-indices = { workspace = true }
pallet-nomination-pools = { workspace = true }
pallet-preimage = { workspace = true }
pallet-proxy = { workspace = true }
pallet-message-queue = { workspace = true }
pallet-rc-migrator = { workspace = true }
pallet-referenda = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-staking = { workspace = true }
pallet-state-trie-migration = { workspace = true }
pallet-vesting = { workspace = true }
pallet-treasury = { workspace = true }
pallet-timestamp = { workspace = true }
polkadot-parachain-primitives = { workspace = true }
polkadot-runtime-common = { workspace = true }
polkadot-runtime-constants = { workspace = true }
runtime-parachains = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
serde = { features = ["derive"], optional = true, workspace = true }
sp-application-crypto = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
hex-literal = { workspace = true }
hex = { workspace = true }
xcm = { workspace = true }
xcm-builder = { workspace = true }
xcm-executor = { workspace = true }
pallet-ah-ops = { workspace = true }

[features]
default = ["std"]
std = [
	"chrono/std",
	"codec/std",
	"cumulus-primitives-core/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"hex/std",
	"log/std",
	"pallet-ah-ops/std",
	"pallet-asset-rate/std",
	"pallet-bags-list/std",
	"pallet-balances/std",
	"pallet-bounties/std",
	"pallet-conviction-voting/std",
	"pallet-fast-unstake/std",
	"pallet-indices/std",
	"pallet-message-queue/std",
	"pallet-multisig/std",
	"pallet-nomination-pools/std",
	"pallet-preimage/std",
	"pallet-proxy/std",
	"pallet-rc-migrator/std",
	"pallet-referenda/std",
	"pallet-scheduler/std",
	"pallet-staking/std",
	"pallet-state-trie-migration/std",
	"pallet-timestamp/std",
	"pallet-treasury/std",
	"pallet-vesting/std",
	"polkadot-parachain-primitives/std",
	"polkadot-runtime-common/std",
	"runtime-parachains/std",
	"scale-info/std",
	"serde",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm/std",
]
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-ah-ops/runtime-benchmarks",
	"pallet-asset-rate/runtime-benchmarks",
	"pallet-bags-list/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-bounties/runtime-benchmarks",
	"pallet-conviction-voting/runtime-benchmarks",
	"pallet-fast-unstake/runtime-benchmarks",
	"pallet-indices/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-nomination-pools/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-rc-migrator/runtime-benchmarks",
	"pallet-referenda/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-state-trie-migration/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"runtime-parachains/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-ah-ops/try-runtime",
	"pallet-asset-rate/try-runtime",
	"pallet-bags-list/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-bounties/try-runtime",
	"pallet-conviction-voting/try-runtime",
	"pallet-fast-unstake/try-runtime",
	"pallet-indices/try-runtime",
	"pallet-message-queue/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-nomination-pools/try-runtime",
	"pallet-preimage/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-rc-migrator/try-runtime",
	"pallet-referenda/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-state-trie-migration/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-vesting/try-runtime",
	"polkadot-runtime-common/try-runtime",
	"runtime-parachains/try-runtime",
	"sp-runtime/try-runtime",
]
