[package]
name = "coretime-kusama-runtime"
description = "Kusama's Coretime parachain runtime"
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.9", default-features = false, features = ["derive"] }
hex-literal = "0.4.1"
log = { version = "0.4.20", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.196", optional = true, features = ["derive"] }

# Local
kusama-runtime-constants = { path = "../../../relay/kusama/constants", default-features = false}
system-parachains-constants = { path = "../../constants", default-features = false }

# Substrate
frame-benchmarking = { default-features = false, optional = true, version = "29.0.0" }
frame-executive = { default-features = false , version = "29.0.0" }
frame-support = { default-features = false , version = "29.0.0" }
frame-system = { default-features = false , version = "29.0.0" }
frame-system-benchmarking = { default-features = false, optional = true , version = "29.0.0" }
frame-system-rpc-runtime-api = { default-features = false , version = "27.0.0" }
frame-try-runtime = { default-features = false, optional = true , version = "0.35.0" }
pallet-aura = { default-features = false, version = "28.0.0", features = ["experimental"] }
pallet-authorship = { default-features = false , version = "29.0.0" }
pallet-balances = { default-features = false , version = "29.0.0" }
pallet-message-queue = { default-features = false , version = "32.0.0" }
pallet-broker = { version = "0.7.0", default-features = false }
pallet-multisig = { default-features = false , version = "29.0.0" }
pallet-proxy = { default-features = false, version = "29.0.0" }
pallet-session = { default-features = false , version = "29.0.0" }
pallet-timestamp = { default-features = false , version = "28.0.0" }
pallet-transaction-payment = { default-features = false , version = "29.0.0" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false , version = "29.0.0" }
pallet-utility = { default-features = false , version = "29.0.0" }
sp-api = { default-features = false , version = "27.0.0" }
sp-block-builder = { version = "27.0.0", default-features = false }
sp-consensus-aura = { default-features = false, version = "0.33.0" }
sp-core = { default-features = false, version = "29.0.0" }
sp-inherents = { default-features = false, version = "27.0.0" }
sp-genesis-builder = { default-features = false , version = "0.8.0" }
sp-offchain = { default-features = false, version = "27.0.0" }
sp-runtime = { default-features = false, version = "32.0.0" }
sp-session = { default-features = false, version = "28.0.0" }
sp-std = { default-features = false, version = "14.0.0" }
sp-storage = { default-features = false, version = "20.0.0" }
sp-transaction-pool = { default-features = false, version = "27.0.0" }
sp-version = { default-features = false, version = "30.0.0" }

# Polkadot
pallet-xcm = { default-features = false, version = "8.0.3" }
pallet-xcm-benchmarks = { default-features = false, optional = true , version = "8.0.2" }
polkadot-core-primitives = { default-features = false, version = "8.0.0" }
polkadot-parachain-primitives = { default-features = false, version = "7.0.0" }
polkadot-runtime-common = { default-features = false, version = "8.0.1" }
xcm = { package = "staging-xcm", default-features = false, version = "8.0.1" }
xcm-builder = { package = "staging-xcm-builder", default-features = false, version = "8.0.1" }
xcm-executor = { package = "staging-xcm-executor", default-features = false, version = "8.0.1" }

# Cumulus
cumulus-pallet-aura-ext = { default-features = false , version = "0.8.0" }
cumulus-pallet-parachain-system = { default-features = false, features = ["parameterized-consensus-hook",] , version = "0.8.1" }
cumulus-pallet-session-benchmarking = { default-features = false, version = "10.0.0" }
cumulus-pallet-xcm = { default-features = false , version = "0.8.0" }
cumulus-pallet-xcmp-queue = { default-features = false , version = "0.8.0" }
cumulus-primitives-aura = { default-features = false, version = "0.8.0" }
cumulus-primitives-core = { default-features = false , version = "0.8.0" }
cumulus-primitives-utility = { default-features = false , version = "0.8.1" }
emulated-integration-tests-common = { version = "4.0.0" }
pallet-collator-selection = { default-features = false , version = "10.0.0" }
parachain-info = { package = "staging-parachain-info", default-features = false , version = "0.8.0" }
parachains-common = { default-features = false , version = "8.0.0" }

[dev-dependencies]
parachains-runtimes-test-utils = { version = "8.0.0" }

[build-dependencies]
substrate-wasm-builder = { optional = true , version = "18.0.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-pallet-aura-ext/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-session-benchmarking/std",
	"cumulus-pallet-xcm/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-primitives-aura/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-utility/std",
	"frame-benchmarking?/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-benchmarking?/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-try-runtime?/std",
	"log/std",
	"pallet-aura/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-broker/std",
	"pallet-collator-selection/std",
	"pallet-message-queue/std",
	"pallet-multisig/std",
	"pallet-proxy/std",
	"pallet-session/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-utility/std",
	"pallet-xcm-benchmarks?/std",
	"pallet-xcm/std",
	"parachain-info/std",
	"parachains-common/std",
	"polkadot-core-primitives/std",
	"polkadot-parachain-primitives/std",
	"polkadot-runtime-common/std",
	"kusama-runtime-constants/std",
	"scale-info/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-storage/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]

runtime-benchmarks = [
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-session-benchmarking/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-primitives-utility/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-broker/runtime-benchmarks",
	"pallet-collator-selection/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-xcm-benchmarks/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]

try-runtime = [
	"cumulus-pallet-aura-ext/try-runtime",
	"cumulus-pallet-parachain-system/try-runtime",
	"cumulus-pallet-xcm/try-runtime",
	"cumulus-pallet-xcmp-queue/try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-broker/try-runtime",
	"pallet-collator-selection/try-runtime",
	"pallet-message-queue/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-session/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-xcm/try-runtime",
	"parachain-info/try-runtime",
	"polkadot-runtime-common/try-runtime",
	"sp-runtime/try-runtime",
]

experimental = ["pallet-aura/experimental"]

fast-runtime = []
