extensions:
  client:
    endpoints:
      - wss://sys.ibp.network/coretime-kusama
      - wss://coretime-kusama.dotters.network
  event_bus:
  substrate_api:
    stale_timeout_seconds: 180
  telemetry:
    provider: none
  cache:
    default_ttl_seconds: 3600
    default_size: 1000
  merge_subscription:
    keep_alive_seconds: 120
  server:
    port: {{PORT}}
    listen_address: '127.0.0.1'
    max_connections: 2000
    max_batch_size: 10
    http_methods:
      - path: /health
        method: system_health
      - path: /liveness
        method: chain_getBlockHash
    cors: all
  rate_limit:
    connection:
      burst: 100
      period_secs: 1
    ip:
      burst: 1000
      period_secs: 10
    use_xff: false
  prometheus:
    port: 9616
    listen_address: "127.0.0.1"
    label: "coretime-kusama"

middlewares:
  methods:
    - delay
    - response
    - inject_params
    - cache
    - upstream
  subscriptions:
    - merge_subscription
    - upstream

rpcs: substrate
