[package]
name = "collectives-polkadot-emulated-chain"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Collectives Polkadot emulated chain used for integration tests"
publish = false

[dependencies]
serde_json = "1.0.111"

# Substrate
sp-core = { version = "28.0.0" }
sp-runtime = { version = "31.0.1" }
frame-support = { version = "28.0.0" }

# Cumulus
parachains-common = { version = "7.0.0" }
cumulus-primitives-core = { version = "0.7.0" }
emulated-integration-tests-common = { version = "3.0.0" }

# Runtimes
collectives-polkadot-runtime = { path = "../../../../../../system-parachains/collectives/collectives-polkadot" }
system-parachains-constants = { path = "../../../../../../system-parachains/constants" }
