[package]
name = "bp-bridge-hub-polkadot"
description = "Primitives of BridgeHubPolkadot parachain runtime."
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

# Local
kusama-runtime-constants = { workspace = true }
polkadot-runtime-constants = { workspace = true }
system-parachains-constants = { workspace = true }

# Bridge Dependencies
bp-bridge-hub-cumulus = { workspace = true }
bp-runtime = { workspace = true }
bp-messages = { workspace = true }
snowbridge-core = { workspace = true }

# Substrate Based Dependencies
frame-support = { workspace = true }
sp-api = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Polkadot
xcm = { workspace = true }

[features]
default = ["std"]
std = [
	"bp-bridge-hub-cumulus/std",
	"bp-messages/std",
	"bp-runtime/std",
	"frame-support/std",
	"kusama-runtime-constants/std",
	"polkadot-runtime-constants/std",
	"snowbridge-core/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
	"system-parachains-constants/std",
	"xcm/std",
]
