[package]
name = "bp-bridge-hub-polkadot"
description = "Primitives of BridgeHubPolkadot parachain runtime."
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

# Local
kusama-runtime-constants = { path = "../../../../relay/kusama/constants", default-features = false }
polkadot-runtime-constants = { path = "../../../../relay/polkadot/constants", default-features = false }
system-parachains-constants = { path = "../../../constants", default-features = false }

# Bridge Dependencies
bp-bridge-hub-cumulus = { default-features = false , version = "0.8.0" }
bp-runtime = { default-features = false , version = "0.8.0" }
bp-messages = { default-features = false , version = "0.8.0" }
snowbridge-core = { default-features = false , version = "0.1.0" }

# Substrate Based Dependencies
frame-support = { default-features = false, version = "29.0.0" }
sp-api = { default-features = false, version = "27.0.0" }
sp-runtime = { default-features = false, version = "32.0.0" }
sp-std = { default-features = false , version = "14.0.0" }

# Polkadot
xcm = { package = "staging-xcm", default-features = false, version = "8.0.1" }

[features]
default = [ "std" ]
std = [
	"bp-bridge-hub-cumulus/std",
	"bp-messages/std",
	"bp-runtime/std",
	"frame-support/std",
	"kusama-runtime-constants/std",
	"polkadot-runtime-constants/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
	"system-parachains-constants/std",
	"xcm/std",
]
