[package]
name = "polkadot-system-emulated-network"
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Polkadot System emulated network"
publish = false

[dependencies]

# Cumulus
emulated-integration-tests-common = { workspace = true }

# Runtimes
asset-hub-polkadot-emulated-chain = { workspace = true }
bridge-hub-polkadot-emulated-chain = { workspace = true }
collectives-polkadot-emulated-chain = { workspace = true }
coretime-polkadot-emulated-chain = { workspace = true }
penpal-emulated-chain = { workspace = true }
polkadot-emulated-chain = { workspace = true }
people-polkadot-emulated-chain = { workspace = true }

[features]
runtime-benchmarks = [
	"asset-hub-polkadot-emulated-chain/runtime-benchmarks",
	"bridge-hub-polkadot-emulated-chain/runtime-benchmarks",
	"collectives-polkadot-emulated-chain/runtime-benchmarks",
	"coretime-polkadot-emulated-chain/runtime-benchmarks",
	"penpal-emulated-chain/runtime-benchmarks",
	"people-polkadot-emulated-chain/runtime-benchmarks",
	"polkadot-emulated-chain/runtime-benchmarks",
]
