[package]
name = "polkadot-system-emulated-network"
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Polkadot System emulated network"
publish = false

[dependencies]

# Cumulus
emulated-integration-tests-common = { workspace = true }

# Runtimes
asset-hub-polkadot-emulated-chain = { path = "../../chains/parachains/assets/asset-hub-polkadot" }
bridge-hub-polkadot-emulated-chain = { path = "../../chains/parachains/bridges/bridge-hub-polkadot" }
collectives-polkadot-emulated-chain = { path = "../../chains/parachains/collectives/collectives-polkadot" }
penpal-emulated-chain = { path = "../../chains/parachains/testing/penpal" }
polkadot-emulated-chain = { path = "../../chains/relays/polkadot" }
