[package]
name = "kusama-system-emulated-network"
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Kusama System emulated network"
publish = false

[dependencies]

# Cumulus
emulated-integration-tests-common = { workspace = true }

# Runtimes
asset-hub-kusama-emulated-chain = { workspace = true }
bridge-hub-kusama-emulated-chain = { workspace = true }
kusama-emulated-chain = { workspace = true }
penpal-emulated-chain = { workspace = true }
people-kusama-emulated-chain = { workspace = true }
