[package]
name = "kusama-runtime-constants"
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
smallvec = "1.13.1"

frame-support = { default-features = false , version = "27.0.0" }
primitives = { package = "polkadot-primitives", default-features = false , version = "6.0.0" }
runtime-common = { package = "polkadot-runtime-common", default-features = false , version = "6.0.0" }
sp-runtime = { default-features = false , version = "30.0.1" }
sp-weights = { default-features = false , version = "26.0.0" }
sp-core = { default-features = false , version = "27.0.0" }

xcm = { package = "staging-xcm", default-features = false , version = "6.0.0" }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"primitives/std",
	"runtime-common/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-weights/std",
	"xcm/std"
]
