[package]
name = "kusama-runtime-constants"
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
smallvec = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }

frame-support = { workspace = true }
polkadot-primitives = { workspace = true }
polkadot-runtime-common = { workspace = true }
sp-runtime = { workspace = true }
sp-weights = { workspace = true }
sp-core = { workspace = true }
sp-trie = { workspace = true, optional = true }
pallet-remote-proxy = { workspace = true }

xcm-builder = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"pallet-remote-proxy/std",
	"polkadot-primitives/std",
	"polkadot-runtime-common/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-trie?/std",
	"sp-weights/std",
	"xcm-builder/std",
]
fast-runtime = []
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"pallet-remote-proxy/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-trie",
	"xcm-builder/runtime-benchmarks",
]
