[package]
name = "kusama-runtime-constants"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
smallvec = "1.8.0"

frame-support = { default-features = false , version = "23.0.0" }
primitives = { package = "polkadot-primitives", default-features = false , version = "2.0.0" }
runtime-common = { package = "polkadot-runtime-common", default-features = false , version = "2.0.0" }
sp-runtime = { default-features = false , version = "26.0.0" }
sp-weights = { default-features = false , version = "22.0.0" }
sp-core = { default-features = false , version = "23.0.0" }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"primitives/std",
	"runtime-common/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-weights/std",
]
