[package]
name = "pallet-ct-migrator"
description = "Migrates registrar and HRMP state with their deposits from the relay chain to the Coretime chain. Coretime-chain side."
license = "Apache-2.0"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
migrator-types = { workspace = true }
registrar-primitives = { workspace = true }
hrmp-primitives = { workspace = true }
codec = { workspace = true, features = ["max-encoded-len"] }
scale-info = { workspace = true, features = ["derive"] }
frame-support = { workspace = true }
frame-system = { workspace = true }
log = { workspace = true }
pallet-proxy = { workspace = true }
polkadot-parachain-primitives = { workspace = true }
sp-runtime = { workspace = true }
xcm = { workspace = true }
pallet-message-queue = { workspace = true }
cumulus-primitives-core = { workspace = true }

[dev-dependencies]
pallet-balances = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
	"hrmp-primitives/std",
	"log/std",
	"migrator-types/std",
	"pallet-message-queue/std",
	"pallet-proxy/std",
	"polkadot-parachain-primitives/std",
	"registrar-primitives/std",
	"scale-info/std",
	"sp-runtime/std",
	"xcm/std",
]
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-message-queue/try-runtime",
	"pallet-proxy/try-runtime",
	"sp-runtime/try-runtime",
]
