[package]
name = "kusama-emulated-chain"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Kusama emulated chain"
publish = false

[dependencies]
serde_json = "1.0.104"

# Substrate
sp-core = { default-features = false, version = "25.0.0" }
sp-runtime = { default-features = false, version = "28.0.0" }
sp-authority-discovery = { default-features = false , version = "23.0.0" }
sp-consensus-babe = { default-features = false , version = "0.29.0" }
beefy-primitives = { package = "sp-consensus-beefy", default-features = false , version = "10.0.0" }
grandpa-primitives = { package = "sp-consensus-grandpa", default-features = false , version = "10.0.0" }
pallet-im-online = { default-features = false, version = "24.0.0" }

# Polkadot
polkadot-primitives = { default-features = false , version = "4.0.0" }
kusama-runtime-constants = { path = "../../../../../relay/kusama/constants", default-features = false }
kusama-runtime = { package = "staging-kusama-runtime", path = "../../../../../relay/kusama", default-features = false }

# Cumulus
parachains-common = { default-features = false, version = "4.0.0" }
#emulated-integration-tests-common = { default-features = false, version = "1.0.0" }
emulated-integration-tests-common = { path = "../../../common", default-features = false }

[features]
default = [ "std" ]

std = [
    "sp-core/std",
    "sp-runtime/std",
    "sp-authority-discovery/std",
    "sp-consensus-babe/std",
    "beefy-primitives/std",
    "grandpa-primitives/std",
    "polkadot-primitives/std",
    "kusama-runtime-constants/std",
    "kusama-runtime/std",
    "parachains-common/std",
    "pallet-im-online/std",
]
