[package]
name = "bp-asset-hub-polkadot"
description = "Primitives of AssetHubPolkadot parachain runtime."
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.9", default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

# Local
system-parachains-constants = { path = "../../../constants", default-features = false }

# Bridge Dependencies
bp-xcm-bridge-hub-router = { default-features = false , version = "0.7.0" }

# Substrate Based Dependencies
frame-support = { default-features = false, version = "29.0.0" }
sp-std = { default-features = false, version = "14.0.0" }

# Polkadot
xcm = { package = "staging-xcm", default-features = false, version = "8.0.1" }

[features]
default = [ "std" ]
std = [
	"bp-xcm-bridge-hub-router/std",
	"codec/std",
	"frame-support/std",
	"scale-info/std",
	"sp-std/std",
	"system-parachains-constants/std",
	"xcm/std"
]
