[package]
name = "kusama-emulated-chain"
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Kusama emulated chain used for integration tests"
publish = false

[dependencies]

# Substrate
sp-core = { workspace = true, default-features = true }
authority-discovery-primitives = { package = "sp-authority-discovery", version = "27.0.0" }
babe-primitives = { package = "sp-consensus-babe", version = "0.33.0" }
beefy-primitives = { package = "sp-consensus-beefy", version = "14.0.0" }
grandpa = { package = "sc-consensus-grandpa", version = "0.20.0" }

# Polkadot
polkadot-primitives = { workspace = true, default-features = true }

# Cumulus
parachains-common = { workspace = true, default-features = true }
emulated-integration-tests-common = { workspace = true }

# Runtimes
kusama-runtime-constants = { path = "../../../../../relay/kusama/constants" }
kusama-runtime = {  package = "staging-kusama-runtime", path = "../../../../../relay/kusama" }
