[package]
name = "kusama-emulated-chain"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Kusama emulated chain used for integration tests"
publish = false

[dependencies]
serde_json = "1.0.111"

# Substrate
sp-core = { version = "28.0.0" }
sp-runtime = { version = "31.0.1" }
authority-discovery-primitives = { package = "sp-authority-discovery", version = "26.0.0" }
babe-primitives = { package = "sp-consensus-babe", version = "0.32.0" }
beefy-primitives = { package = "sp-consensus-beefy", version = "13.0.0" }
grandpa = { package = "sc-consensus-grandpa", version = "0.19.0" }
pallet-im-online = { version = "27.0.0" }

# Polkadot
polkadot-primitives = { version = "7.0.0" }

# Cumulus
parachains-common = { version = "7.0.0" }
emulated-integration-tests-common = { version = "3.0.0" }

# Runtimes
kusama-runtime-constants = { path = "../../../../../relay/kusama/constants" }
kusama-runtime = {  package = "staging-kusama-runtime", path = "../../../../../relay/kusama" }
