# Print help
help:
	@just --list

snapshot RUNTIME:
	#!/usr/bin/env bash
	set -ex

	# Check if {{RUNTIME}}.snap and ah-{{RUNTIME}}.snap exist, otherwise download
	if [ ! -f {{RUNTIME}}.snap ]; then
		echo "Downloading {{RUNTIME}}.snap"
		curl -sL 'https://tasty.limo/uploads/{{RUNTIME}}.snap.lz4' -o {{RUNTIME}}.snap.lz4
		echo "Decompressing {{RUNTIME}}.snap.lz4"
		lz4 -d {{RUNTIME}}.snap.lz4 {{RUNTIME}}.snap
	else
		echo "{{RUNTIME}}.snap already exists"
	fi

	if [ ! -f ah-{{RUNTIME}}.snap ]; then
		echo "Downloading ah-{{RUNTIME}}.snap"
		curl -sL 'https://tasty.limo/uploads/ah-{{RUNTIME}}.snap.lz4' -o ah-{{RUNTIME}}.snap.lz4
		echo "Decompressing ah-{{RUNTIME}}.snap.lz4"
		lz4 -d ah-{{RUNTIME}}.snap.lz4 ah-{{RUNTIME}}.snap
	else
		echo "ah-{{RUNTIME}}.snap already exists"
	fi
