# Various checks to verify the cargo workspace and its crates are correctly configured.
name: "Workspace features"

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
  workflow_dispatch:

# cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check workspace features
    runs-on: ubuntu-22.04

    steps:
      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Zepter
        run: cargo install --locked -q zepter && zepter --version

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Dont clone historic commits.

      - name: Check features
        run: |
          zepter run check
          # We will add this to the config file once its stabilized. Just run it in the CI for now.
          zepter transpose dep lift-to-workspace 'regex:.*'
