name: "Rustfmt (check)"

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
  workflow_dispatch:

jobs:
  rustfmt:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set common env variables
        run: sed "" .github/env >> $GITHUB_ENV

      - name: Install nightly toolchain
        run: rustup toolchain install "nightly-$RUST_NIGHTLY_VERSION" --profile minimal --component rustfmt

      - name: Rustfmt (check)
        run: cargo +nightly-$RUST_NIGHTLY_VERSION fmt --all -- --check
