name: "Rustfmt (check)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  rustfmt:
    runs-on: ubuntu-22.04

    steps:

      - name: Install toolchains
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt
          override: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Rustfmt (check)
        run:  cargo fmt --all -- --check
