name: "Rustfmt (check)"

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
  workflow_dispatch:

# Cancel a currently running workflow from the same PR, branch or tag when a new workflow is
# triggered (ref https://stackoverflow.com/a/72408109)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rustfmt:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set rust version via common env file
        run: cat .github/env >> $GITHUB_ENV

      - name: Install nightly toolchain
        run: rustup toolchain install "nightly-$RUST_NIGHTLY_VERSION" --profile minimal --component rustfmt

      - name: Rustfmt (check)
        run: cargo +nightly-$RUST_NIGHTLY_VERSION fmt --all -- --check
