name: Create Release

on:
  push:
    branches: [ "main" ]
    paths: [ "CHANGELOG.md" ]
  workflow_dispatch:

jobs:
  collect-release-information:
    runs-on: self-hosted
    outputs:
      should-release: ${{ steps.run.outputs.should-release }}
      version: ${{ steps.run.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: run
        run: |
          echo "should-release=$(.github/changelog-processor.py CHANGELOG.md --should-release)" >> $GITHUB_OUTPUT
          echo "version=$(.github/changelog-processor.py CHANGELOG.md --print-latest-version)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  runtime-matrix:
    needs: [ collect-release-information ]
    if: needs.collect-release-information.outputs.should-release == '1'
    runs-on: self-hosted
    outputs:
      runtime: ${{ steps.runtime.outputs.runtime }}
    steps:
      - uses: actions/checkout@v4
      - id: runtime
        run: |
          TASKS=$(echo $(cat .github/workflows/runtimes-matrix.json) | sed 's/ //g' )
          echo $TASKS
          echo "runtime=$TASKS" >> $GITHUB_OUTPUT

  build-runtimes:
    needs: [ runtime-matrix ]
    continue-on-error: true
    runs-on: self-hosted
    strategy:
      matrix:
        runtime: ${{ fromJSON(needs.runtime-matrix.outputs.runtime) }}
    env:
      PROD_FEATURES: "--features on-chain-release-build"
      TRY_RUNTIME_LOGGING_FEATURES: "--features try-runtime,metadata-hash"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cache target dir
        uses: actions/cache@v4
        with:
          path: "${{ github.workspace }}/${{ matrix.runtime.path }}/target"
          key: srtool-target-${{ matrix.runtime.path }}-${{ matrix.runtime.name }}-${{ github.sha }}
          restore-keys: |
            srtool-target-${{ matrix.runtime.path }}-${{ matrix.runtime.name }}-
            srtool-target-${{ matrix.runtime.path }}-

      - name: Build ${{ matrix.runtime.name }}
        id: srtool_build
        uses: paritytech/srtool-actions@v0.9.4
        env:
          BUILD_OPTS: ${{ env.PROD_FEATURES }}
        with:
          chain: ${{ matrix.runtime.name }}
          package: ${{ matrix.runtime.package }}
          runtime_dir: ${{ matrix.runtime.path }}
          profile: "production"
